---

 - name: Check LLDP, OSPF and BGP neighbors
   hosts: all
   vars:
    wait_seconds: 60
   tasks:

      - name: pause for {{ wait_seconds | int }} second(s)
        ansible.builtin.pause:
          seconds: "{{ wait_seconds | int }}"

      - ios_command:
          commands:
          - show lldp neighbors
          - show ip ospf neighbor
          - show ip bgp summary
        register: results

      - template:
          src: Check.j2
          dest: "Summary/{{inventory_hostname}}.txt"
        delegate_to: localhost
    




