---

hostname: Edge-2

loopback: { ip: 3.3.3.3 }

interfaces: 
 - name: Ethernet1/1
   ip: 192.168.34.4
   subnet: 255.255.255.0

ospf_as: 10
router_id: 3.3.3.3
networks:
 - 192.168.34.0 0.0.0.255
 - 3.3.3.3 0.0.0.0

bgp_as: 10
neighbors:
 - ip: 1.1.1.1
   bgp_as: 10

 - ip: 2.2.2.2
   bgp_as: 10




